## app config
spring.application.name=RackMaster
server.port = 9630
spring.thymeleaf.cache = true

## connect to database
spring.datasource.driver-class-name = org.postgresql.Driver
spring.datasource.url = jdbc:postgresql://172.27.12.216:5432/rackmaster?serverTimeZone=UTC
spring.datasource.username = postgres
spring.datasource.password = 5UD0_5U_4LT3R_U53R_N10R_#..

## config JPA
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true

